### ISSUE TITLE
plotMarkerExpression: scaling issue

### ISSUE THREAD

**Issue by lgeistlinger** [ccb-hms/scDiagnostics#13]
As pointed out by @drisso and @deepayan, expression levels for one gene might not be directly comparable between reference and query datasets due to differences in scale. I think the library-size normalization and log-transformation should put them in a somewhat comparable range, but we might need something like a z-score transformation on top to make the scale comparable.

**Comment by AnthonyChristidis** [comment]
A normal rank transformation is now being applied to the logcounts for the marker of interest.
