### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by lgeistlinger** [ccb-hms/scDiagnostics#41]
I think the [README](https://github.com/ccb-hms/scDiagnostics/blob/main/README.md) should be updated to only contain the package summary and installation instructions. The "Usage" section incl. R code, examples, and figures should all be removed from the README and instead point to https://ccb-hms.github.io/scDiagnostics/ which updates dynamically upon pushing to the repo. That means the static figure collection in https://github.com/ccb-hms/scDiagnostics/tree/main/man/figures can also be removed now.

**Comment by AnthonyChristidis** [comment]
This change has ben implemented.
