### ISSUE TITLE
README

### ISSUE THREAD

**Issue by lgeistlinger** [ccb-hms/scDiagnostics#79]
Two different installation methods are introduced for installing the release (via `BiocManager::install`) and the development version (via `remotes::install_github`) of the package.

Note that `BiocManager::install` can be used for both. In fact, `BiocManager::install` simply invokes `remotes::install_github` when provided a github account and repo string, that means here: `BiocManager::install("ccb-hms/scDiagnostics")`.

This will simplify installation instructions for end users.

Further:

Under installation instructions for [Release Version](https://github.com/ccb-hms/scDiagnostics?tab=readme-ov-file#release-version):
- NOTE: you will need the [BiocManager](https://cran.r-project.org/web/packages/BiocManager/index.html) package to install from GitHub. -> NOTE: you will need the [BiocManager](https://cran.r-project.org/web/packages/BiocManager/index.html) package to install from Bioconductor.

Under [Usage](https://github.com/ccb-hms/scDiagnostics?tab=readme-ov-file#usage):
- The complete documentation of each available function in scDiagnostics, which includes implementation details and working examples -> The individual documentation of each available function in scDiagnostics, which includes usage details and executable examples

**Comment by lgeistlinger** [comment]
Below an attempt to make the paragraphs under [Key Features](https://github.com/ccb-hms/scDiagnostics?tab=readme-ov-file#key-features) a bit more concise and precise:

[Visualization of Cell Type Annotations](https://ccb-hms.github.io/scDiagnostics/articles/VisualizationTools.html): illustrates the distributions of cell type annotations of the query and reference dataset, allowing the user to identify potential differences in the cell type composition between datasets.

[Evaluation of QC and Annotation Scores](https://ccb-hms.github.io/scDiagnostics/articles/QCandAnnotationScores.html): provides functionality for assessing the impact of frequently used QC criteria on the cell type annotation confidence, allowing the user to identify systematic relationships between QC metrics and the predicted cell type categories.

[Evaluation of Dataset and Marker Gene Alignment](https://ccb-hms.github.io/scDiagnostics/articles/DatasetAlignment.html): provides functionality for assessing dataset alignment through quantitative comparison of query-to-reference projections in reduced dimension space. Additional functionality for assessing marker gene expression across datasets allows the user to identify potential misalignments between reference and query on the level of individual genes.

[Statistical Measures to Assess Dataset Alignment](https://ccb-hms.github.io/scDiagnostics/articles/StatisticalMeasures.html): _shouldn't that be part of the previous paragraph / functionality category?_

[Detection of Annotation Anomalies](https://ccb-hms.github.io/scDiagnostics/articles/AnnotationAnomalies.html): Focuses on identifying inconsistencies or anomalies in cell type annotations between the query and reference datasets through comparison of expert annotations with annotations derived from automated methods. By highlighting discrepancies that could be indicative of potential errors, this feature aids in refining and improving the accuracy and reliability of cell type classifications.

[Analysis of Distances Between Specific Cells and Cell Populations](https://ccb-hms.github.io/scDiagnostics/articles/CellDistancesDiagnostics.html): looks good

**Comment by AnthonyChristidis** [comment]
Thanks for your very clear feedback, @lgeistlinger. For the "Statistical Measures to Assess Dataset Alignment" there is indeed an argument that could be made to merge that collection of functions to the previous collection of functions in "Evaluation of Dataset and Marker Gene Alignment". It is really a matter of taste to create this hierarchy of different functionalities, but I would argue separating them is a good idea solely based on the fact that combining these two sets of functions together could make it a little too long/overwhelming in a single vignette.

**Comment by AnthonyChristidis** [comment]
These issues have been resolved.
