### ISSUE TITLE
vignettes: formatting issues

### ISSUE THREAD

**Issue by lgeistlinger** [ccb-hms/scDiagnostics#80]
- in the [cell distances vignette](https://ccb-hms.github.io/scDiagnostics/articles/CellDistancesDiagnostics.html):

<img width="780" alt="Screenshot 2024-09-15 at 12 41 09 PM" src="https://github.com/user-attachments/assets/8c055278-e3ed-4f15-9cef-86b6a3729890">

- in the [dataset alignment vignette](https://ccb-hms.github.io/scDiagnostics/articles/DatasetMarkerGeneAlignment.html):

1)
<img width="781" alt="Screenshot 2024-09-15 at 12 46 14 PM" src="https://github.com/user-attachments/assets/fecc76c2-a60d-4847-ba0a-25b90f210064">

2) 
<img width="795" alt="Screenshot 2024-09-15 at 12 48 13 PM" src="https://github.com/user-attachments/assets/4fa009cf-3fb9-43bf-8e05-db7939a517e2">

- in the [anomaly vignette](https://ccb-hms.github.io/scDiagnostics/articles/AnnotationAnomalies.html):

<img width="785" alt="Screenshot 2024-09-15 at 12 51 33 PM" src="https://github.com/user-attachments/assets/f6001ce6-7481-4c5d-9622-2f40f9dbd233">

**Comment by AnthonyChristidis** [comment]
These issues have been resolved.
